import cProfile
import pstats
import io
from pstats import SortKey

from asgn_4_package.lib_raw import StringAnalysis


def test_profile_main():
    pr = cProfile.Profile()
    pr.enable()

    # Sample DNA sequences for benchmarking
    data_1 = "gtctgggagtctagataagtaaccgcgacggatcaaatttgtgcggcggtacataacctgagttcctatggtgagggatccgcttttcacttgaggagctattctaaagttccgcggctctacacgtgcccgtctaaaaaaacaaaagtcacgctacatctagcaagaacagagttcatatggactgctgacttatatagccaagtcaccggtttcaccacgatgtatacgttgtcgggtcgaaatgtggttaggactcttgcgctaatgatccaataagctttggtccccggttcgagctgccgaggaaggcgggccaaaacatcccgggaacgcgattctgctctacacacagcatgactgtcccaaataagatcctccgacggcgtccccatgacggattcatctagttgacggccaacggactccccagcgtgggagatgtaagaaacgcagatcctaggagactaccatgctcttaaggcggtactcaggcacgtccacattatctaagcgttcgatcggtaaccgattagagcgacaggattcaaccgtgaaaagctaactaggatggccggcaaatgcaggtgcgggcaggtcaagagataataaaagtgggtcttcgctgcgtcttgtagggtgctggggcgagtattagtcactacagataagttttgcggatggcgaaggggggggctaaacttcgcagtagctcccgaacgtcagtctcgtcttgcgccctcagtcaaggccggctccattggcgggtctcagggggctcggggtatttcatatcaaggccctagcatgatatccagagcaataggtcgcaggctgcaaatgaagggataaatggtccgagaggcgctcctaatagatttgggggatgacgatacgggtgaggtcatataggagctagtgccaacgaaagttcctattgtgcccttgatcgaggtgctatgttacacagtagtaaacgagcggtcctcagtttttgactaaaatcggacggctcgaatggactctctgaccggttggtggaacccggtgccagattactggtagattttgtatcggttcaaacgatcgacggcgcaattcacatgccgatatgcctatccccccaggatcctggtaaggaatcaatccaagactacgatgttgcagagggtattttgtccgctacgctttccagccgtagggcacggtccacagatttccgcgatggaaaaatcgccagccttttatgttatcgcactggaataagattaccgttggatcggactgcttcatccctgacttgcgattcgctacaaagaactgcacaacgcacctcctatactcgtacctgtaggtggatcaagtatctttatgtcgcgattaaattgcctcgtcatggatggtactcggcaccgggaaggtttggatatgcctgcacttcacagaggttagggttcctgactcgcggcataccttaaccccgggctcttctaggtggtacggggcacagccgaaaaaaaaaggtcgtctggcctcatcaaataaccaaccacaactgtccacctaattccctgacagcttagccatctaactttccgaagtcaaccagtacgcaattatttaccgcgcatgtctcgcgtagccggcggtaacgatgttggtggtgttctcgctgacaagagtcctaaggaggcgacacaattatgtttcggattgtcacgtctcatattcacctcactccataagaactacccagctactttttctggacccgtcgctaaggaatcgaagatagtgcggattcgtcaatgcatacgtgataatttggtccgggcggtcatacgtactgacacgacgtgggtagattgcgtccagtatgcatcaaaattcgatcgaggagtggtgtccatgggcggatagggatttcaaaccgtaactatctttagctggccagattaccatagggcggagtggtggagtggggagagctagtcagtggt"
    data_2 = "gtctgggagtctagataagtaaccgcgacggatcaaatttgtgcggcggtacataacctgagttcctatggtgagggatccgcttttcacttgaggagctattctaaagttccgcggctctacacgtgcccgtctaaaaaaacaaaagtcacgctacatctagcaagaacagagttcatatggactgctgacttatatagccaagtcaccggtttcaccacgatgtatacgttgtcgggtcgaaatgtggttaggactcttgcgctaatgatccaataagctttggtccccggttcgagctgccgaggaaggcgggccaaaacatcccgggaacgcgattctgctctacacacagcatgactgtcccaaataagatcctccgacggcgtccccatgacggattcatctagttgacggccaacggactccccagcgtgggagatgtaagaaacgcagatcctaggagactaccatgctcttaaggcggtactcaggcacgtccacattatctaagcgttcgatcggtaaccgattagagcgacaggattcaaccgtgaaaagctaactaggatggccggcaaatgcaggtgcgggcaggtcaagagataataaaagtgggtcttcgctgcgtcttgtagggtgctggggcgagtattagtcactacagataagttttgcggatggcgaaggggggggctaaacttcgcagtagctcccgaacgtcagtctcgtcttgcgccctcagtcaaggccggctccattggcgggtctcagggggctcggggtatttcatatcaaggccctagcatgatatccagagcaataggtcgcaggctgcaaatgaagggataaatggtccgagaggcgctcctaatagatttgggggatgacgatacgggtgaggtcatataggagctagtgccaacgaaagttcctattgtgcccttgatcgaggtgctatgttacacagtagtaaacgagcggtcctcagtttttgactaaaatcggacggctcgaatggactctctgaccggttggtggaacccggtgccagattactggtagattttgtatcggttcaaacgatcgacggcgcaattcacatgccgatatgcctatccccccaggatcctggtaaggaatcaatccaagactacgatgttgcagagggtattttgtccgctacgctttccagccgtagggcacggtccacagatttccgcgatggaaaaatcgccagccttttatgttatcgcactggaataagattaccgttggatcggactgcttcatccctgacttgcgattcgctacaaagaactgcacaacgcacctcctatactcgtacctgtaggtggatcaagtatctttatgtcgcgattaaattgcctcgtcatggatggtactcggcaccgggaaggtttggatatgcctgcacttcacagaggttagggttcctgactcgcggcataccttaaccccgggctcttctaggtggtacggggcacagccgaaaaaaaaaggtcgtctggcctcatcaaataaccaaccacaactgtccacctaattccctgacagcttagccatctaactttccgaagtcaaccagtacgcaattatttaccgcgcatgtctcgcgtagccggcggtaacgatgttggtggtgttctcgctgacaagagtcctaaggaggcgacacaattatgtttcggattgtcacgtctcatattcacctcactccataagaactacccagctactttttctggacccgtcgctaaggaatcgaagatagtgcggattcgtcaatgcatacgtgataatttggtccgggcggtcatacgtactgacacgacgtgggtagattgcgtccagtatgcatcaaaattcgatcgaggagtggtgtccatgggcggatagggatttcaaaccgtaactatctttagctggccagattaccatagggcggagtggtggagtggggagagctagtcagtggt"

    string_analysis = StringAnalysis(data_1, data_2)
    string_analysis.analyze()

    pr.disable()

    s = io.StringIO()
    sortby = SortKey.CUMULATIVE
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print(s.getvalue())


test_profile_main()
